### ISSUE TITLE
Marlin crash when running ConformalTracking with SiD_o2_v03

### ISSUE THREAD

**Issue by protopopescu** [iLCSoft/MarlinTrk#14]
Marlin reconstruction crashes with 

***********************************************
 A runtime error occured - (uncaught exception):
      vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)
 Marlin will have to be terminated, sorry.
 ***********************************************
when running reconstruction on single particle tracks, as described below. We believe the crash happens in MarlinTrkUtils.cc. Could you please help us debug this?

 - OS version: SLC6
 - Compiler version: GCC 4.9.3
 - Package version: ILCSOFT=/cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v02-00-01
 - Reproduced by: 
```
source /cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v02-00-01/init_ilcsoft.sh
mkdir tempTest
cd tempTest
python $lcgeo_DIR/example/lcio_particle_gun.py
# We entered the information for 10 or 20 GeV Pions here)
ddsim --compactFile SiD/compact/SiD_o2_v03/SiD_o2_v03.xml --runType  batch --inputFile mcparticles_20GeV_Pions_918.slcio --outputFile=SiD_o2_v03_20GeV_Sakshi_918.slcio --numberOfEvents 1000
wget https://github.com/iLCSoft/MarlinTrk/files/2581668/SiDReconstruction_o2_v03_calib1ct3_sakshi2.xml.zip
unzip SiDReconstruction_o2_v03_calib1ct3_sakshi2.xml.zip
# We just put in the output file we generated here as the lcio input for SiDReconstruction_o2_v03_calib1ct3_sakshi2.xml, and changed the output file name accordingly. 
Marlin SiDReconstruction_o2_v03_calib1ct3_sakshi2.xml
```

 - Input: [SiDReconstruction_o2_v03_calib1ct3_sakshi2.xml.zip](https://github.com/iLCSoft/MarlinTrk/files/2581668/SiDReconstruction_o2_v03_calib1ct3_sakshi2.xml.zip)
 - Output: [error.log](https://github.com/iLCSoft/MarlinTrk/files/2581681/error.log)
 - Goal: testing ConformalTracking with SiD_o2_v03

**Comment by protopopescu** [comment]
Same details can be found in https://www.evernote.com/l/AJ2LhmMZQtlM77niFdYNP37-ozZcMKsN-zU

**Comment by andresailer** [comment]
I edited your message for easily reproducing the problem. I just use the particle_gun script from lcgeo but I guess you have modified that, so you should make that script also available.
With the commands given like this, one can just copy and paste them into the terminal to run and reproduce the problem.
Still some files are missing...
```
 ***********************************************
 A runtime error occured - (uncaught exception):
      gear::ParseException: GearXML::createGearMgr error in file [gear_SiD_o2_v03.xml, row: 0, col: 0] : Failed to open file
 Marlin will have to be terminated, sorry.
 ***********************************************
```

**Comment by protopopescu** [comment]
Well, I guess my files will be okay for reproducing the crash, so here they are
[lcio_particle_gun.py.zip](https://github.com/iLCSoft/MarlinTrk/files/2605041/lcio_particle_gun.py.zip)
[gear_SiD_o2_v03.xml.zip](https://github.com/iLCSoft/MarlinTrk/files/2605042/gear_SiD_o2_v03.xml.zip)

**Comment by andresailer** [comment]
Or you could make sure that it will be enough to reproduce the problem and update the list of commands in the first post of this thread.

**Comment by protopopescu** [comment]
Ok, to clarify, these were the exact files I used to produce the crash illustrated in the attached error.log file. I was waiting for Sakshi will attach theirs, hence the delay in replying to your request. 
Lots of thanks, Andre, for looking into this!

**Comment by sakshin15** [comment]
Hi! 
Here are my gear and lcio particle gun files. 
[lcio_particle_gun.zip](https://github.com/iLCSoft/MarlinTrk/files/2609383/lcio_particle_gun.zip)
[gear_SiD_o2_v03.zip](https://github.com/iLCSoft/MarlinTrk/files/2609384/gear_SiD_o2_v03.zip)

**Comment by sakshin15** [comment]
Updated commands: 

1) source /cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v02-00-01/init_ilcsoft.sh
2) vi example/lcio_particle_gun.py
Here, I changed the nevt to 1000, and set the momenta to 10, and theta to 85. 
The particle chosen was pions. The outfile generated is "mcparticles_10_pions.slcio"
3) python example/lcio_particle_gun.py
4) ddsim --compactFile SiD/compact/SiD_o2_v03/SiD_o2_v03.xml --runType batch --inputFile mcparticles_10_pions.slcio --outputFile=afterddsim_10_pions.slcio --numberOfEvents 1000
5) vi SiDReconstruction_o2_v03_calib1ct3_sakshi.xml
In line 63, I inserted afterddsim_10_pions.slcio and changed the LCIOOutputFile (line 191) name accordingly. 
6) Marlin SiDReconstruction_o2_v03_calib1ct3_sakshi.xml

This is where we end up getting the error. I have attached my gear file, the simpleHCalScript, and the Pandora files I am using here as well. They are all extracted in the same lcgeo folder. 
Please let me know if you need me to attach any other additional information as well. 
 
[gear_SiD_o2_v03.zip](https://github.com/iLCSoft/MarlinTrk/files/2622957/gear_SiD_o2_v03.zip)
[simpleHcalscript (3).zip](https://github.com/iLCSoft/MarlinTrk/files/2622964/simpleHcalscript.3.zip)
[PandoraLikelihoodData9EBin.zip](https://github.com/iLCSoft/MarlinTrk/files/2622966/PandoraLikelihoodData9EBin.zip)
[PandoraSettingsDefault.zip](https://github.com/iLCSoft/MarlinTrk/files/2622968/PandoraSettingsDefault.zip)

**Comment by sakshin15** [comment]
[new files.zip](https://github.com/iLCSoft/MarlinTrk/files/2622989/new.files.zip)
UPDATE: here are is the folder containing the new files. Please disregard the previously sent files. All the files except for the lcio_particle_gun.py are extracted in the lcgeo folder. The lcio_particle_gun.py is in the example folder in lcgeo.

**Comment by protopopescu** [comment]
Thank you, Sakshi!

**Comment by protopopescu** [comment]
Any progress or new ideas on this?

**Comment by andresailer** [comment]
I have been quite busy with various documents, so I didn't have time to try this again. And it would be extremely helpful if you could update the list of commands to include the download and extraction of all files, and then make sure that the commands can run through starting from a clean shell. I.e. all input and output file names are matching and that all necessary files are present, and no manual changes to steering files are necessary.

I.e extend this list of commands:
```bash
source /cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v02-00-01/init_ilcsoft.sh
mkdir tempTest
cd tempTest
python $lcgeo_DIR/example/lcio_particle_gun.py
# We entered the information for 10 or 20 GeV Pions here)
ddsim --compactFile SiD/compact/SiD_o2_v03/SiD_o2_v03.xml --runType  batch --inputFile mcparticles_20GeV_Pions_918.slcio --outputFile=SiD_o2_v03_20GeV_Sakshi_918.slcio --numberOfEvents 1000
wget https://github.com/iLCSoft/MarlinTrk/files/2581668/SiDReconstruction_o2_v03_calib1ct3_sakshi2.xml.zip
unzip SiDReconstruction_o2_v03_calib1ct3_sakshi2.xml.zip
# We just put in the output file we generated here as the lcio input for SiDReconstruction_o2_v03_calib1ct3_sakshi2.xml, and changed the output file name accordingly. 
Marlin SiDReconstruction_o2_v03_calib1ct3_sakshi2.xml
```
PS: I am also wondering if the simulation of 1000 particles is really necessary to reproduce the problem, or this number can be reduced

**Comment by protopopescu** [comment]
I've attached an archive that contains all the files necessary to reproduce this bug. You just need access to /cvmfs/ilc.desy.de/. Please unzip the archive, cd issue14/ and execute ./runme.sh. 
[issue14.zip](https://github.com/iLCSoft/MarlinTrk/files/2787584/issue14.zip)

**Comment by andresailer** [comment]
It is not ConformalTracking that crashes, but the MyExtrToTracker_InOut.
Things run through when I disable this processor (And as its collection seem not to be used anywhere.)

There are these warnings given by this processor:
```
[ WARNING "MyExtrToTracker_InOut"] ExtrToTracker::getGeoInfo - exception in retriving number of modules per layer for subdetector : SiTrackerEndcap : ObjectExtensions::extension: The object has no extension of type 1F6E7BA869721FD8.
[ WARNING "MyExtrToTracker_InOut"] ExtrToTracker::getGeoInfo - exception in retriving number of modules per layer for subdetector : SiTrackerForward : ObjectExtensions::extension: The object has no extension of type 1F6E7BA869721FD8.
```
I think the detector types used for SiTrackerEndcap and SiTracker Forward to not add the ZDiskPetal DataStruct, which is used by the ExtrToTracker processor.

**Comment by andresailer** [comment]
Or it is related to the surfaces, when I change the plugins in SiTrackerEndcap and Forward to the DD4hep_GenericSurfaceInstallerPlugin the crash also disappears...

**Comment by protopopescu** [comment]
Thank you, Andre!
