### ISSUE TITLE
"MarlinTrk/MarlinKalTest.h" need by other packages

### ISSUE THREAD

**Issue by shaojunlu** [iLCSoft/MarlinTrk#3]
This header "MarlinTrk/MarlinKalTest.h" was inside here.
https://github.com/iLCSoft/MarlinTrk/tree/master/include/MarlinTrk

It is needed by "MarlinTrk/MarlinKalTest.h" has been removed, please update here. #9
https://github.com/iLCSoft/Clupatra/blob/master/src/clupatra_new.cc#L17

and "MarlinTrk/MarlinKalTest.h" not exist anymore, please update this code #2
https://github.com/iLCSoft/KiTrackMarlin/blob/master/src/Tools/Fitter.cc#L12

Please update them.

**Comment by petricm** [comment]
Resolved
